node {

  // config 
  //def to = emailextrecipients([
  //        [$class: 'CulpritsRecipientProvider'],
  //        [$class: 'DevelopersRecipientProvider'],
  //        [$class: 'RequesterRecipientProvider']
  def to = '$DEFAULT_RECIPIENTS'
  //])

  // job
  try {
    stage('build') {
      println('so far so good...')
    }
    stage('test') {
      println('A test has failed!')
      sh 'exit 1'
    }
  } catch(e) {
    // mark build as failed
    currentBuild.result = "FAILURE";
    // set variables
    def subject = "Jenkins Test"
    def content = 'Test email from Jenkins build failure'

    // send email
    //if(to != null && !to.isEmpty()) {
      emailext(body: content, mimeType: 'text/html',
         replyTo: '$DEFAULT_REPLYTO', subject: subject,
         to: '$DEFAULT_RECIPIENTS', attachLog: false )
    //}

    // mark current build as a failure and throw the error
    throw e;
  }
}
